### ISSUE TITLE
Contributing to the codebase?!

### ISSUE THREAD

**Issue by RachelHamieh** [iTzSharkSV/Hyper#15]
Greetings!
I have alot of ideas on how to improve the templates, wanna see them @iTzSharkSV?!

**Comment by iTzSharkSV** [comment]
> wanna see them @iTzSharkSV?!

Sure, go ahead... 

All contributions are appreciated! You can start by checking our [Code of Conduct](https://github.com/iTzSharkSV/Hyper/blob/Main/Docs/CODE_OF_CONDUCT.md) File then submitting an issue addressing the change you wanna make _(Each change should have its separate issue)_; Alternatively you can mail/discuss the changes directly with me on discord **iTzShark#0690**

& thanks for your interest in `Hyper` 😃
